services:
    quarkus.jvm:
        container_name: quarkus.jvm
        hostname: quarkus.jvm
        image: quarkus.jvm
        build:
            context: ./benchmark-quarkus
            dockerfile:  ./src/main/docker/Dockerfile.jvm
        ports:
            - 8080:8080

    quarkus.graalvm:
        container_name: quarkus.graalvm
        hostname: quarkus.graalvm
        image: quarkus.graalvm
        build:
            context: ./benchmark-quarkus
            dockerfile: ./src/main/docker/Dockerfile.graalvm
        ports:
            - 8082:8080

    quarkus.native:
        container_name: quarkus.native
        hostname: quarkus.native
        image: quarkus.native
        build:
            context: ./benchmark-quarkus
            dockerfile: ./src/main/docker/Dockerfile.native
        ports:
            - 8081:8080

    spring.graalvm:
        container_name: spring.graalvm
        hostname: spring.graalvm
        image: spring.graalvm
        build:
            context: ./benchmark-spring
            dockerfile: ./src/main/docker/Dockerfile.graalvm
        ports:
            - 8084:8080

    spring.jvm:
        container_name: spring.jvm
        hostname: spring.jvm
        image: spring.jvm
        build:
            context: ./benchmark-spring
            dockerfile: ./src/main/docker/Dockerfile.jvm
        ports:
            - 8085:8080

    spring.native.demo:
        container_name: spring.native.demo
        hostname: spring.native.demo
        image: spring.native.demo
        build:
            context: ./demo-spring-native
            dockerfile: Dockerfile
        ports:
            - 8090:8080

    micronaut.jvm:
        container_name: micronaut.jvm
        hostname: micronaut.jvm
        image: micronaut.jvm
        build:
            context: ./benchmark-micronaut
            dockerfile: ./src/main/docker/Dockerfile.jvm
        ports:
            - 8086:8080

    micronaut.graalvm:
        container_name: micronaut.graalvm
        hostname: micronaut.graalvm
        image: micronaut.graalvm
        build:
            context: ./benchmark-micronaut
            dockerfile: ./src/main/docker/Dockerfile.graalvm
        ports:
            - 8087:8080


